directory_path: "C:/Users/TUF/OneDrive/Рабочий стол/GenPrep/SideProjectsPython/python_core/cli_malware_scanner/test_directory"
log_filename: "log_file.log"
keywords: 
  - "virus"
  - "trojan"
  - "malware"
timestamp_format: "%Y-%m-%d %H:%M:%S"
