detection_result: true
engine_version: 7.5.1
file_hash: d41d8cd98f00b204e9800998ecf8427e
file_name: ransomware_sample.exe
scan_date: '2025-06-02'
scan_info:
    definitions_version: '2025-06-01'
    scan_duration_seconds: 50
    scanned_by: MalwareScannerPro
severity: Critical
threat_name: Ransom.Locky
